apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-transaction
  namespace: default
spec:
  selector:
    matchLabels:
      app: transaction
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/default/sa/gateway-sa"
